= dechat_es6a2

image:https://travis-ci.org/Arquisoft/dechat_es6a2.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es6a2"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_es6a2/badge.svg?branch=master["Coverage status", link="https://coveralls.io/github/Arquisoft/dechat_es6a2?branch=master"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es6a2?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es6a2&utm_campaign=Badge_Grade"]
image:https://img.shields.io/badge/documentation-AsciiDoc-FF69A4.svg[link="https://arquisoft.github.io/dechat_es6a2/documentation.html"]
image:https://img.shields.io/badge/version-1.0.3-green.svg[link="https://arquisoft.github.io/dechat_es6a2/"]

== App Webpage
You can give it a try at https://arquisoft.github.io/dechat_es6a2/ (WIP)

== Authors

Jorge Álvarez Fidalgo & Othmane Bakhtaoui

Developed on *Notepad++* and *Atom*.

== Getting started

In order to run the app locally, you have to https://github.com/Arquisoft/dechat_es6a2/wiki[install Nodes.js®]

== Build documentation

You can checkout our project's documentation https://arquisoft.github.io/dechat_es6a2/documentation.html[here].

The documentation is done in http://asciidoc.org/[adoc] format
using the https://arc42.org/[arc42] templates and transformed into html using https://asciidoctor.org/docs/install-toolchain/asciiDoctor[AsciiDoctor]. 

To generate the documentation from the https://github.com/Arquisoft/dechat_es6a2/tree/master/adocs[adocs] folder, just run the following command :

----
docs
----

== Compile and run

To run the application locally, you have to install http-server:

----
 npm install http-server -g
----

And then execute the following command:

----
 run
----

It will show some IP addresses where the application will be available.

== Testing

There are unit tests using mocha at
 https://github.com/Arquisoft/dechat_es6a2/tree/master/tests[tests].

There are also some https://cucumber.io/[Cucumber based tests] defined at
 https://github.com/Arquisoft/dechat_es6a2/tree/master/step-definitions[step-definitions].

To run tests, execute:

----
npm test
----
